name: posprovider
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.3.4
  flutter_riverpod: ^2.3.4
  realm: ^1.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3



flutter:

  
